name: Tests

on: [pull_request]
env:
  BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    container:
      image: docker://bitcli/bit:latest
    steps:
      - name: Bit config
        run: |
          bit config set interactive false
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token ${{ env.BIT_TOKEN }}
          bit config set no_warnings true
          bit config set error_reporting true
          bit config set user.name symphony_backend
      - uses: actions/checkout@v2      
      - name: Config registry
        run: |  
          npm config set @bit:registry https://node.bit.dev
          npm config set @teambit:registry https://node.bit.dev
      - name: Config npm
        run: npm config set always-auth=true && npm config set //node.bit.dev/:_authToken\=${{ env.BIT_TOKEN }} && npm config list
      - name: Install dependencies
        run: bit install
      - name: Bit compile
        run: bit compile && bit compile && bit compile
      - name: Bit test
        run: bit test
      - uses: actions/upload-artifact@v2
        with:
          name: debug-log
          path: ~/Library/Caches/Bit/logs